# Generated by Django 3.1.4 on 2020-12-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandName', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('W', 'Women'), ('M', 'Men'), ('B', 'Both')], max_length=1)),
                ('locationID', models.CharField(max_length=50)),
                ('availability', models.BooleanField(default=False)),
            ],
        ),
    ]
