# Generated by Django 3.1.4 on 2020-12-16 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='partner',
            table='partners',
        ),
    ]
